C4Context
    accTitle: TrueFriends
    accDescr: Components

    Person(user, "Пользователь", "Пользователь использует МП для планирования досуга")

    Container_Boundary(app, "Сервис", "") {
        Component(mobile_app, "Мобильное приложение", "Swift", "Мобильное приложение,в котором пользователь может подобрать себе мероприятие")
    }

    Container_Boundary(backend, "Бэкенд", "") {
        Component(api, "API", "Rest API", "Предоставляет способы и правила для взаимодействия")
        Component(processing, "Обработка данных", "Python", "Обрабатывает данные")
    }

    Container_Boundary(parsers, "Парсеры", "") {
        Component(kudago, "KUDAGO", "Python", "Сбор данныхс сайта кудаго")
        Component(tg, "TG", "Python", "Сбор данных из профильных тг каналов")
        Component(mp, "MP", "Python", "Предложения в мп, которые оставляют пользователи через заявки")
    }

    Container_Boundary(storage, "Хранилище", "") {
        Component(database, "База данных", "SQL Database", "Хранит сырые данныемероприятий и мест из различных источников и обработанные данные")
        Component(hdfs, "HDFS", "HDFS", "Хранит данные и работает с ними")
    }

    Container_Boundary(modeling, "ML", "") {
        Component(ml, "ML модели", "Python, PyTorch", "Категоризируют места и мероприятия, данные для обучения хранит в HDFS")
        Component(spark, "Spark", "Обработка и анализ данных", "Обрабатывает данных")
    }


    Rel(user, mobile_app, "Использует")
    Rel(mobile_app, api, "Отправляет запросы")
    Rel(api, processing, "Отправляет запросы")
    Rel(processing, database, "Работает с данными")
    Rel(kudago, spark, "Парсинг данных с сайта Кудаго")
    Rel(tg, spark, "Парсинг данных из профильных тг каналов")
    Rel(mp, spark, "Парсинг данных из МП")
    Rel(spark, hdfs, "Передает данные")
    Rel(spark, ml, "Использует")
    Rel(spark, database, "Хранит")